Release/basket about us
frrrolova/e-commerce pull request #77
Opened 2024-06-17 20:58 UTC by REGEMLER

### Task:
 [Sprint 4](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint%234.md)
### Screenshot: 
![image](https://github.com/frrrolova/e-commerce/assets/87263562/99957948-e3e5-42bc-946b-9eed8e4b2198)
![image](https://github.com/frrrolova/e-commerce/assets/87263562/6aecec9c-79bb-4882-9c75-bd5228f7052e)

### Deployment: [deploy](https://plantastic-green-shop.netlify.app/)
### Repo: [repo](https://github.com/frrrolova/e-commerce)
### Trello: [trello](https://trello.com/b/krg6NjEG/ecommerce-application)

#### Done 17.06.2024 / deadline 18.05.2024
#### Score: 60 / 60
 - Code Review Participation (10 points)
 - No Merges Without Approvals (10 points)
 -  Pull Request Descriptions (10 points)
 - Task Board Management (10 points)
 - Active Participation in Development Discussions (5 points)
 - Unit Test Coverage (15 points)

In this sprint, we concentrated on enhancing the Detailed Product Page, building the Basket page, and further enhancing the Catalog page. These enhancements  included features such as a comprehensive view of a product with the option to add  or remove the product from the cart, increase or decrease the quantity of the product, and display a clear indicator if the product is already in the user's shopping cart.
Our team has also worked on features for the Basket page like displaying a list of items  added to the basket, increasing or decreasing  the quantity of each item, removing items from the basket, displaying the subtotal and total prices, and a button  for proceeding to the checkout page.
For the Catalog page, we have implemented interactive product cards  and shopping cart integration. We have also implemented pagination to handle a large number of products efficiently. Finally we have implemented about us page

2024-06-17 22:27 UTC, frrrolova requested changes

2024-06-17 22:35 UTC, tanykos requested changes
In general the code is well-organized, the application has an attractive and user friendly interface. Mentioned changes in comments should enhance the readability, maintainability, and user experience.

2024-06-18 00:28 UTC, frrrolova approved these changes

2024-06-18 00:29 UTC, tanykos approved these changes

2024-06-18 00:30 UTC, merged

2024-06-27 05:34 UTC, igor2000xp reviewed
Good job, but your files are very large. It would be better to create separate helper functions and split long components into smaller ones.

2024-06-27 05:34 UTC, igor2000xp commented on src/components/BasketProduct/BasketProduct.tsx
Good job, but your files are very large. It would be better to create separate helper functions and split long components into smaller ones.